2018-05-12 15:46:51 pid:1 PDOException: SQLSTATE[HY000] [2002] 由于目标计算机积极拒绝，无法连接。
 in F:\cloud\projects\api\vendor\workerman\mysql\src\Connection.php:1711
Stack trace:
#0 F:\cloud\projects\api\vendor\workerman\mysql\src\Connection.php(1711): PDO->__construct('mysql:dbname=xs...', 'root', 'Fancy@Qingguo.....', Array)
#1 F:\cloud\projects\api\vendor\workerman\mysql\src\Connection.php(1698): Workerman\MySQL\Connection->connect()
#2 F:\cloud\projects\api\http.php(12): Workerman\MySQL\Connection->__construct('127.0.0.1', '3306', 'root', 'Fancy@Qingguo.....', 'xserver')
#3 [internal function]: {closure}(Object(App))
#4 F:\cloud\projects\api\vendor\workerman\workerman\Worker.php(2115): call_user_func(Object(Closure), Object(App))
#5 F:\cloud\projects\api\app_http.php(92): Workerman\Worker->run()
#6 F:\cloud\projects\api\vendor\workerman\workerman\Worker.php(1189): App->run()
#7 F:\cloud\projects\api\vendor\workerman\workerman\Worker.php(1132): Workerman\Worker::forkWorkersForWindows()
#8 F:\cloud\projects\api\vendor\workerman\workerman\Worker.php(466): Workerman\Worker::forkWorkers()
#9 F:\cloud\projects\api\http.php(34): Workerman\Worker::runAll()
#10 {main}
2018-05-12 15:46:52 pid:1 Worker process terminated
2018-05-12 15:46:53 pid:1 PDOException: SQLSTATE[HY000] [2002] 由于目标计算机积极拒绝，无法连接。
 in F:\cloud\projects\api\vendor\workerman\mysql\src\Connection.php:1711
Stack trace:
#0 F:\cloud\projects\api\vendor\workerman\mysql\src\Connection.php(1711): PDO->__construct('mysql:dbname=xs...', 'root', 'Fancy@Qingguo.....', Array)
#1 F:\cloud\projects\api\vendor\workerman\mysql\src\Connection.php(1698): Workerman\MySQL\Connection->connect()
#2 F:\cloud\projects\api\http.php(12): Workerman\MySQL\Connection->__construct('127.0.0.1', '3306', 'root', 'Fancy@Qingguo.....', 'xserver')
#3 [internal function]: {closure}(Object(App))
#4 F:\cloud\projects\api\vendor\workerman\workerman\Worker.php(2115): call_user_func(Object(Closure), Object(App))
#5 F:\cloud\projects\api\app_http.php(92): Workerman\Worker->run()
#6 F:\cloud\projects\api\vendor\workerman\workerman\Worker.php(1189): App->run()
#7 F:\cloud\projects\api\vendor\workerman\workerman\Worker.php(1132): Workerman\Worker::forkWorkersForWindows()
#8 F:\cloud\projects\api\vendor\workerman\workerman\Worker.php(466): Workerman\Worker::forkWorkers()
#9 F:\cloud\projects\api\http.php(34): Workerman\Worker::runAll()
#10 {main}
2018-05-12 15:46:54 pid:1 Worker process terminated
2018-05-12 15:46:56 pid:1 PDOException: SQLSTATE[HY000] [2002] 由于目标计算机积极拒绝，无法连接。
 in F:\cloud\projects\api\vendor\workerman\mysql\src\Connection.php:1711
Stack trace:
#0 F:\cloud\projects\api\vendor\workerman\mysql\src\Connection.php(1711): PDO->__construct('mysql:dbname=xs...', 'root', 'Fancy@Qingguo.....', Array)
#1 F:\cloud\projects\api\vendor\workerman\mysql\src\Connection.php(1698): Workerman\MySQL\Connection->connect()
#2 F:\cloud\projects\api\http.php(12): Workerman\MySQL\Connection->__construct('127.0.0.1', '3306', 'root', 'Fancy@Qingguo.....', 'xserver')
#3 [internal function]: {closure}(Object(App))
#4 F:\cloud\projects\api\vendor\workerman\workerman\Worker.php(2115): call_user_func(Object(Closure), Object(App))
#5 F:\cloud\projects\api\app_http.php(92): Workerman\Worker->run()
#6 F:\cloud\projects\api\vendor\workerman\workerman\Worker.php(1189): App->run()
#7 F:\cloud\projects\api\vendor\workerman\workerman\Worker.php(1132): Workerman\Worker::forkWorkersForWindows()
#8 F:\cloud\projects\api\vendor\workerman\workerman\Worker.php(466): Workerman\Worker::forkWorkers()
#9 F:\cloud\projects\api\http.php(34): Workerman\Worker::runAll()
#10 {main}
2018-05-12 15:46:57 pid:1 Worker process terminated
2018-05-12 15:46:59 pid:1 PDOException: SQLSTATE[HY000] [2002] 由于目标计算机积极拒绝，无法连接。
 in F:\cloud\projects\api\vendor\workerman\mysql\src\Connection.php:1711
Stack trace:
#0 F:\cloud\projects\api\vendor\workerman\mysql\src\Connection.php(1711): PDO->__construct('mysql:dbname=xs...', 'root', 'Fancy@Qingguo.....', Array)
#1 F:\cloud\projects\api\vendor\workerman\mysql\src\Connection.php(1698): Workerman\MySQL\Connection->connect()
#2 F:\cloud\projects\api\http.php(12): Workerman\MySQL\Connection->__construct('127.0.0.1', '3306', 'root', 'Fancy@Qingguo.....', 'xserver')
#3 [internal function]: {closure}(Object(App))
#4 F:\cloud\projects\api\vendor\workerman\workerman\Worker.php(2115): call_user_func(Object(Closure), Object(App))
#5 F:\cloud\projects\api\app_http.php(92): Workerman\Worker->run()
#6 F:\cloud\projects\api\vendor\workerman\workerman\Worker.php(1189): App->run()
#7 F:\cloud\projects\api\vendor\workerman\workerman\Worker.php(1132): Workerman\Worker::forkWorkersForWindows()
#8 F:\cloud\projects\api\vendor\workerman\workerman\Worker.php(466): Workerman\Worker::forkWorkers()
#9 F:\cloud\projects\api\http.php(34): Workerman\Worker::runAll()
#10 {main}
2018-05-12 15:47:00 pid:1 Worker process terminated
2018-05-12 15:47:29 pid:1 PDOException: PDO::__construct(): php_network_getaddresses: getaddrinfo failed: 不知道这样的主机。  in F:\cloud\projects\api\vendor\workerman\mysql\src\Connection.php:1711
Stack trace:
#0 F:\cloud\projects\api\vendor\workerman\mysql\src\Connection.php(1711): PDO->__construct('mysql:dbname=xs...', 'root', 'Fancy@Qingguo.....', Array)
#1 F:\cloud\projects\api\vendor\workerman\mysql\src\Connection.php(1698): Workerman\MySQL\Connection->connect()
#2 F:\cloud\projects\api\http.php(12): Workerman\MySQL\Connection->__construct('xserver.fancygu...', '3306', 'root', 'Fancy@Qingguo.....', 'xserver')
#3 [internal function]: {closure}(Object(App))
#4 F:\cloud\projects\api\vendor\workerman\workerman\Worker.php(2115): call_user_func(Object(Closure), Object(App))
#5 F:\cloud\projects\api\app_http.php(92): Workerman\Worker->run()
#6 F:\cloud\projects\api\vendor\workerman\workerman\Worker.php(1189): App->run()
#7 F:\cloud\projects\api\vendor\workerman\workerman\Worker.php(1132): Workerman\Worker::forkWorkersForWindows()
#8 F:\cloud\projects\api\vendor\workerman\workerman\Worker.php(466): Workerman\Worker::forkWorkers()
#9 F:\cloud\projects\api\http.php(34): Workerman\Worker::runAll()
#10 {main}

Next PDOException: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: 不知道这样的主机。  in F:\cloud\projects\api\vendor\workerman\mysql\src\Connection.php:1711
Stack trace:
#0 F:\cloud\projects\api\vendor\workerman\mysql\src\Connection.php(1711): PDO->__construct('mysql:dbname=xs...', 'root', 'Fancy@Qingguo.....', Array)
#1 F:\cloud\projects\api\vendor\workerman\mysql\src\Connection.php(1698): Workerman\MySQL\Connection->connect()
#2 F:\cloud\projects\api\http.php(12): Workerman\MySQL\Connection->__construct('xserver.fancygu...', '3306', 'root', 'Fancy@Qingguo.....', 'xserver')
#3 [internal function]: {closure}(Object(App))
#4 F:\cloud\projects\api\vendor\workerman\workerman\Worker.php(2115): call_user_func(Object(Closure), Object(App))
#5 F:\cloud\projects\api\app_http.php(92): Workerman\Worker->run()
#6 F:\cloud\projects\api\vendor\workerman\workerman\Worker.php(1189): App->run()
#7 F:\cloud\projects\api\vendor\workerman\workerman\Worker.php(1132): Workerman\Worker::forkWorkersForWindows()
#8 F:\cloud\projects\api\vendor\workerman\workerman\Worker.php(466): Workerman\Worker::forkWorkers()
#9 F:\cloud\projects\api\http.php(34): Workerman\Worker::runAll()
#10 {main}
2018-05-12 15:47:30 pid:1 Worker process terminated
2018-05-12 15:47:31 pid:1 PDOException: PDO::__construct(): php_network_getaddresses: getaddrinfo failed: 不知道这样的主机。  in F:\cloud\projects\api\vendor\workerman\mysql\src\Connection.php:1711
Stack trace:
#0 F:\cloud\projects\api\vendor\workerman\mysql\src\Connection.php(1711): PDO->__construct('mysql:dbname=xs...', 'root', 'Fancy@Qingguo.....', Array)
#1 F:\cloud\projects\api\vendor\workerman\mysql\src\Connection.php(1698): Workerman\MySQL\Connection->connect()
#2 F:\cloud\projects\api\http.php(12): Workerman\MySQL\Connection->__construct('xserver.fancygu...', '3306', 'root', 'Fancy@Qingguo.....', 'xserver')
#3 [internal function]: {closure}(Object(App))
#4 F:\cloud\projects\api\vendor\workerman\workerman\Worker.php(2115): call_user_func(Object(Closure), Object(App))
#5 F:\cloud\projects\api\app_http.php(92): Workerman\Worker->run()
#6 F:\cloud\projects\api\vendor\workerman\workerman\Worker.php(1189): App->run()
#7 F:\cloud\projects\api\vendor\workerman\workerman\Worker.php(1132): Workerman\Worker::forkWorkersForWindows()
#8 F:\cloud\projects\api\vendor\workerman\workerman\Worker.php(466): Workerman\Worker::forkWorkers()
#9 F:\cloud\projects\api\http.php(34): Workerman\Worker::runAll()
#10 {main}

Next PDOException: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: 不知道这样的主机。  in F:\cloud\projects\api\vendor\workerman\mysql\src\Connection.php:1711
Stack trace:
#0 F:\cloud\projects\api\vendor\workerman\mysql\src\Connection.php(1711): PDO->__construct('mysql:dbname=xs...', 'root', 'Fancy@Qingguo.....', Array)
#1 F:\cloud\projects\api\vendor\workerman\mysql\src\Connection.php(1698): Workerman\MySQL\Connection->connect()
#2 F:\cloud\projects\api\http.php(12): Workerman\MySQL\Connection->__construct('xserver.fancygu...', '3306', 'root', 'Fancy@Qingguo.....', 'xserver')
#3 [internal function]: {closure}(Object(App))
#4 F:\cloud\projects\api\vendor\workerman\workerman\Worker.php(2115): call_user_func(Object(Closure), Object(App))
#5 F:\cloud\projects\api\app_http.php(92): Workerman\Worker->run()
#6 F:\cloud\projects\api\vendor\workerman\workerman\Worker.php(1189): App->run()
#7 F:\cloud\projects\api\vendor\workerman\workerman\Worker.php(1132): Workerman\Worker::forkWorkersForWindows()
#8 F:\cloud\projects\api\vendor\workerman\workerman\Worker.php(466): Workerman\Worker::forkWorkers()
#9 F:\cloud\projects\api\http.php(34): Workerman\Worker::runAll()
#10 {main}
2018-05-12 15:47:32 pid:1 Worker process terminated
2018-05-12 15:47:57 pid:1 PDOException: SQLSTATE[HY000] [1130] Host '61.49.68.34' is not allowed to connect to this MySQL server in F:\cloud\projects\api\vendor\workerman\mysql\src\Connection.php:1711
Stack trace:
#0 F:\cloud\projects\api\vendor\workerman\mysql\src\Connection.php(1711): PDO->__construct('mysql:dbname=xs...', 'root', 'Fancy@Qingguo.....', Array)
#1 F:\cloud\projects\api\vendor\workerman\mysql\src\Connection.php(1698): Workerman\MySQL\Connection->connect()
#2 F:\cloud\projects\api\http.php(12): Workerman\MySQL\Connection->__construct('x-server.fancyg...', '3306', 'root', 'Fancy@Qingguo.....', 'xserver')
#3 [internal function]: {closure}(Object(App))
#4 F:\cloud\projects\api\vendor\workerman\workerman\Worker.php(2115): call_user_func(Object(Closure), Object(App))
#5 F:\cloud\projects\api\app_http.php(92): Workerman\Worker->run()
#6 F:\cloud\projects\api\vendor\workerman\workerman\Worker.php(1189): App->run()
#7 F:\cloud\projects\api\vendor\workerman\workerman\Worker.php(1132): Workerman\Worker::forkWorkersForWindows()
#8 F:\cloud\projects\api\vendor\workerman\workerman\Worker.php(466): Workerman\Worker::forkWorkers()
#9 F:\cloud\projects\api\http.php(34): Workerman\Worker::runAll()
#10 {main}
2018-05-12 15:47:58 pid:1 Worker process terminated
2018-05-12 15:47:59 pid:1 PDOException: SQLSTATE[HY000] [1130] Host '61.49.68.34' is not allowed to connect to this MySQL server in F:\cloud\projects\api\vendor\workerman\mysql\src\Connection.php:1711
Stack trace:
#0 F:\cloud\projects\api\vendor\workerman\mysql\src\Connection.php(1711): PDO->__construct('mysql:dbname=xs...', 'root', 'Fancy@Qingguo.....', Array)
#1 F:\cloud\projects\api\vendor\workerman\mysql\src\Connection.php(1698): Workerman\MySQL\Connection->connect()
#2 F:\cloud\projects\api\http.php(12): Workerman\MySQL\Connection->__construct('x-server.fancyg...', '3306', 'root', 'Fancy@Qingguo.....', 'xserver')
#3 [internal function]: {closure}(Object(App))
#4 F:\cloud\projects\api\vendor\workerman\workerman\Worker.php(2115): call_user_func(Object(Closure), Object(App))
#5 F:\cloud\projects\api\app_http.php(92): Workerman\Worker->run()
#6 F:\cloud\projects\api\vendor\workerman\workerman\Worker.php(1189): App->run()
#7 F:\cloud\projects\api\vendor\workerman\workerman\Worker.php(1132): Workerman\Worker::forkWorkersForWindows()
#8 F:\cloud\projects\api\vendor\workerman\workerman\Worker.php(466): Workerman\Worker::forkWorkers()
#9 F:\cloud\projects\api\http.php(34): Workerman\Worker::runAll()
#10 {main}
2018-05-12 15:48:00 pid:1 Worker process terminated
2018-05-12 15:48:01 pid:1 PDOException: SQLSTATE[HY000] [1130] Host '61.49.68.34' is not allowed to connect to this MySQL server in F:\cloud\projects\api\vendor\workerman\mysql\src\Connection.php:1711
Stack trace:
#0 F:\cloud\projects\api\vendor\workerman\mysql\src\Connection.php(1711): PDO->__construct('mysql:dbname=xs...', 'root', 'Fancy@Qingguo.....', Array)
#1 F:\cloud\projects\api\vendor\workerman\mysql\src\Connection.php(1698): Workerman\MySQL\Connection->connect()
#2 F:\cloud\projects\api\http.php(12): Workerman\MySQL\Connection->__construct('x-server.fancyg...', '3306', 'root', 'Fancy@Qingguo.....', 'xserver')
#3 [internal function]: {closure}(Object(App))
#4 F:\cloud\projects\api\vendor\workerman\workerman\Worker.php(2115): call_user_func(Object(Closure), Object(App))
#5 F:\cloud\projects\api\app_http.php(92): Workerman\Worker->run()
#6 F:\cloud\projects\api\vendor\workerman\workerman\Worker.php(1189): App->run()
#7 F:\cloud\projects\api\vendor\workerman\workerman\Worker.php(1132): Workerman\Worker::forkWorkersForWindows()
#8 F:\cloud\projects\api\vendor\workerman\workerman\Worker.php(466): Workerman\Worker::forkWorkers()
#9 F:\cloud\projects\api\http.php(34): Workerman\Worker::runAll()
#10 {main}
2018-05-12 15:48:02 pid:1 Worker process terminated
